language: python
python:
  - "3.9"

sudo: false
cache: pip

install: pip install -r reqs.txt
script: sphinx-build -nWT -b dummy source build

after_failure:
  - chmod +x ./restore.sh
  - ./restore.sh
