version: 2

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r reqs.txt
      - run:
          name: buildhtml
          command: sphinx-build -nWT -b dummy source build

workflows:
  version: 2
  build:
    jobs:
      - test